# Generated by Django 2.0.7 on 2018-07-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180711_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideroption',
            name='provider',
        ),
    ]
