# Generated by Django 2.0.7 on 2018-07-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_provideroption_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideroption',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CloudProvider'),
            preserve_default=False,
        ),
    ]
