# Generated by Django 2.0.7 on 2018-07-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180725_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Instance'),
        ),
        migrations.AddField(
            model_name='instance',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.InstanceState'),
        ),
    ]
